apiVersion: apps/v1
kind: Deployment
metadata:
  name: fResult-nginx-deployment
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      app: fResult-nginx-pod
  template:
    metadata:
      labels:
        app: fResult-nginx-pod
    spec:
      containers:
        - image: nginx
          name: fResult-nginx-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          restartPolicy: Always
