apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.myApp.name | default "nginx-default" | quote | upper }}
    {{- if .Values.myConfig.hasValue }}
    release: {{ .Release.Name }}
    {{- end }}
    chartVersion: {{ .Chart.Version }}
    chartApiVersion: {{ .Chart.APIVersion }}
    chartAppVersion: {{ .Chart.AppVersion }}
    chartName: {{ .Chart.Name }}
    valueTest: {{ .Values.myConfig.test }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.myConfig.replicas }}
  selector:
    matchLabels:
      app: nginx-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
