apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.myApp.name | default "nginx-default" | quote | upper }}
    {{- if .Values.myConfig.appEnabled }}
    release: {{ .Release.Name }}
    {{- end }}
    chartVersion: {{ .Chart.Version }}
    chartApiVersion: {{ .Chart.APIVersion }}
    chartAppVersion: {{ .Chart.AppVersion }}
    chartName: {{ .Chart.Name }}
    valueTest: {{ .Values.myConfig.test }}
    data:
    {{- with .Values.myConfig }}
      {{- with .frontend }}
      background: {{ .background }}
      foreground: {{ .foreground }}
      {{- end }}
      {{- with .database }}
      database:   {{ .name }}
      connection: {{ .conn }}
      {{- end }}
    {{- end }}
spec:
  replicas: {{ .Values.myConfig.replicas }}
  selector:
    matchLabels:
      app: nginx-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
